# Generated by Django 6.0 on 2026-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#fff9a8', max_length=20),
        ),
    ]
