# Generated by Django 6.0 on 2025-12-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_quicknote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickNote',
        ),
    ]
